apiVersion: apps/v1
kind: Deployment
metadata:
  name: herman
spec:
  selector:
    matchLabels:
      app: herman
  replicas: 2
  template:
    metadata:
      labels:
        app: herman
    spec:
      containers:
        - name: herman
          image: nanajanashia/argocd-app:1.2
          ports:
            - containerPort: 8080
